---
name: Validate Postman collection
on:
  workflow_call:
    inputs:
      postman-collection-path:
        description: The path to the Postman collection file
        required: false
        default: ./postman/collections/collection.json
        type: string
      postman-collection-patch-path:
        description: The path to the Postman collection patch
        required: false
        type: string
      spec-artifact-name:
        description: The artifact name of the bundled API specification
        required: true
        type: string
      temp-collection-filename:
        description: The filename of the temporarily created collection file
        required: false
        default: generated_collection.json
        type: string
      spec-path:
        description: The path to the OpenAPI specification root file
        required: false
        default: ./specification/openapi.yml
        type: string
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download spec
        id: download-spec
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.spec-artifact-name }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install OpenAPI-to-Postman
        run: npm install -g openapi-to-postmanv2@latest

      - name: Build postman collection
        run: >-
          openapi2postmanv2 -c postman_to_openapi.json
          -s ${{github.workspace}}/${{inputs.spec-path}} -o ${{github.workspace}}/${{inputs.temp-collection-filename}}

      - name: Patch postman collection
        if: ${{ inputs.postman-collection-patch-path }}
        run: >-
          jq -n 'reduce inputs as $i ({}; .* $i)'  ${{github.workspace}}/${{inputs.temp-collection-filename}} ${{ inputs.postman-collection-patch-path }}  > ${{github.workspace}}/${{inputs.temp-collection-filename}}

      - name: Compare collection files
        run: >-
          diff
          <(jq --sort-keys . ${{github.workspace}}/${{inputs.temp-collection-filename}})
          <(jq --sort-keys . ${{inputs.postman-collection-path}})
