---
name: Validate OpenAPI Spec
on:
  workflow_call:
    inputs:
        postman-collection-path:
            description: The path to the Postman collection file
            required: false
            default: ./postman/collections/collection.json
            type: string
        spec-path:
            description: The path to the OpenAPI specification root file
            required: false
            default: ./specification/openapi.yml
            type: string
        temp-collection-filename:
            description: The filename of the temporarily created collection file
            required: false
            default: generated_collection.json
            type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install OpenAPI-to-Postman
        run: npm install -g openapi-to-postmanv2@latest

      - name: Build postman collection
        run: >-
          openapi2postmanv2 -c postman_to_openapi.json
          -s ${{github.workspace}}/${{inputs.spec-path}} -o ${{github.workspace}}/${{inputs.temp-collection-filename}}
    
      - name: Compare collection files
        run: >-
          diff
          <(jq --sort-keys 'del(.info._postman_id)' ${{github.workspace}}/${{inputs.temp-collection-filename}})
          <(jq --sort-keys 'del(.info._postman_id)' ${{inputs.postman-collection-path}})

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest

      - name: Validate configuration
        run: |
          redocly check-config

      - name: Validate specification
        run: |
          redocly lint
