---
    name: Publish API to GitHub
    on:
      workflow_call:
        inputs:
          spec-artifact-name:
            description: The artifact name of the bundled API specification
            required: true
            type: string
          stats-artifact-name:
            description: The artifact name of the API stats file
            required: true
            type: string
          api-root-path:
            description: The root path of the API specification
            required: true
            type: string
          release-tag:
            description: The tag for the Github release
            required: true
            type: string
    
    permissions: {}
    
    jobs:
      release-to-github:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
    
          - name: Download spec
            id: download-spec
            uses: actions/download-artifact@v4
            with:
              name: ${{ inputs.spec-artifact-name }}
    
          - name: Download stats
            id: download-stats
            uses: actions/download-artifact@v4
            with:
              name: ${{ inputs.stats-artifact-name }}
    
          - name: Create GitHub release
            run: gh release create --verify-tag --notes-from-tag ${{ inputs.release-tag }}
            env:
              GH_TOKEN: ${{ github.token }}
    
          - name: Release spec
            run: gh release upload ${{ inputs.release-tag }} ${{ steps.download-spec.outputs.download-path }}/${{inputs.spec-artifact-name }}
            env:
              GH_TOKEN: ${{ github.token }}
    
          - name: Release stats
            run: gh release upload ${{ inputs.release-tag }} ${{ steps.download-stats.outputs.download-path }}/${{inputs.stats-artifact-name }}
            env:
              GH_TOKEN: ${{ github.token }}
    
          - name: Release collection
            run: gh release upload ${{ inputs.release-tag }} ${{ inputs.postman-collection-path }}
            env:
              GH_TOKEN: ${{ github.token }}