---
name: Bundle API
on:
  workflow_call:
    inputs:
      build-dir:
        description: The directory to use for build artifacts
        default: build
        required: false
        type: string
      bundled-spec-filename:
        description: The filename of the bundled API specification
        default: openapi.yaml
        required: false
        type: string
      stats-filename:
        description: The filename of the API statistics file
        default: stats.json
        required: false
        type: string
    outputs:
        spec-artifact-id:
            description: The ID of the bundled specification Github Action artifact
            value: ${{ jobs.bundle.outputs.spec-artifact-id }}
        stats-artifact-id:
            description: The ID of the stats Github Action artifact
            value: ${{ jobs.bundle.outputs.stats-artifact-id }}


jobs:
  bundle:
    runs-on: ubuntu-latest
    outputs:
        spec-artifact-id: ${{ steps.upload-spec.outputs.artifact-id }}
        stats-artifact-id: ${{ steps.upload-stats.outputs.artifact-id }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v1.1.1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest

      - name: Bundle specification
        run: |
          redocly bundle -o ${{inputs.build-dir}}/${{inputs.bundled-spec-filename}}

      - name: Upload specification
        id: upload-spec
        uses: actions/upload-artifact@v4
        with:
            name: ${{inputs.bundled-spec-filename}}
            path: ${{inputs.build-dir}}/${{inputs.bundled-spec-filename}}
            if-no-files-found: error

      - name: Generate stats
        run: |
          redocly stats --format=json > ${{inputs.build-dir}}/${{inputs.stats-filename}}

      - name: Upload stats
        id: upload-stats
        uses: actions/upload-artifact@v4
        with:
            name: ${{inputs.stats-filename}}
            path: ${{inputs.build-dir}}/${{inputs.stats-filename}}
            if-no-files-found: error